kind: pipeline
name: default

steps:
- name: docker
  image: plugins/docker
  settings:
    repo: djeeberjr/l4d2-docker
    username: djeeberjr
    password:
      from_secret: DOCKER_HUB_TOKEN
trigger:
  branch:
  - master
