version: "3"

services:
  l4d2:
    build: .
    environment:
      - CVAR_HOSTNAME=My left 4 dead server
      - CVAR_RCON_PASSWORD=password123
      - CVAR_SV_ALLOW_LOBBY_CONNECT_ONLY=0
      - CVAR_SV_CONSISTENCY=0
      - CAVR_SV_VOICEENABLE=1
      - CVAR_MP_DISABLE_AUTOKICK=1
      - INSECURE=true
      - "MOTD_FILE_CONTENT=Put your MODT here. \n
Multiline is also supported."
      - "HOST_FILE_CONTENT=Same with the host file \n
lalalalal"
    ports:
      - 27015:27015
      - 27015:27015/udp
    volumes:
      - l4d2_game:/home/steam/server
    stdin_open: true
    tty: true
volumes:
  l4d2_game:
    name: l4d2_game

