version: "3"

services:
  l4d2:
    build: .
    environment:
      - CVAR_HOSTNAME=My left 4 dead server
      - CVAR_RCON_PASSWORD=password123
      - CVAR_MP_DISABLE_AUTOKICK=1
    volume:
      - ./motd.txt:/motd.txt:ro
      - ./host:txt:/host.txt:ro
    ports:
      - 27015:27015
      - 27015:27015/udp
